import { describe, expect, it } from "vitest";
import { applyOutboxMutationToState, bootstrapAccountToState, ensureNotLastOwner, requireCanManageMembers, requireCanRead, type BootstrapState, type CloudState, type OutboxMutationArgs } from "./cloudPolicy";
const identity = { provider: "clerk" as const, normalizedIssuer: "https://issuer.example", subject: "external-editor" };
function state(): CloudState { return { users: [{ internalUserId: "u-owner", status: "active" }, { internalUserId: "u-editor", status: "active" }, { internalUserId: "u-viewer", status: "active" }], identityLinks: [{ provider: "clerk", normalizedIssuer: identity.normalizedIssuer, subject: "external-owner", internalUserId: "u-owner", status: "active" }, { ...identity, internalUserId: "u-editor", status: "active" }, { provider: "clerk", normalizedIssuer: identity.normalizedIssuer, subject: "external-viewer", internalUserId: "u-viewer", status: "active" }], workspaces: [{ workspaceId: "ws-a", name: "A", status: "active", revision: 0, policyRevision: 1 }, { workspaceId: "ws-b", name: "B", status: "active", revision: 0, policyRevision: 1 }], memberships: [{ memberId: "m-owner", workspaceId: "ws-a", internalUserId: "u-owner", role: "owner", status: "active", revision: 1 }, { memberId: "m-editor", workspaceId: "ws-a", internalUserId: "u-editor", role: "editor", status: "active", revision: 1 }, { memberId: "m-viewer", workspaceId: "ws-a", internalUserId: "u-viewer", role: "viewer", status: "active", revision: 1 }], devices: [{ deviceId: "d-editor", internalUserId: "u-editor", status: "active" }, { deviceId: "d-viewer", internalUserId: "u-viewer", status: "active" }], deviceLinks: [{ workspaceId: "ws-a", deviceId: "d-editor", internalUserId: "u-editor", memberId: "m-editor", status: "active" }, { workspaceId: "ws-a", deviceId: "d-viewer", internalUserId: "u-viewer", memberId: "m-viewer", status: "active" }], projects: [], tombstones: [], idempotencyKeys: [] }; }
function mutation(overrides: Partial<OutboxMutationArgs> = {}): OutboxMutationArgs { return { workspaceId: "ws-a", deviceId: "d-editor", clientMutationId: "one", idempotencyKey: "ws-a:d-editor:one", baseRevision: 0, recordType: "project", recordId: "p-one", operation: "create", ...overrides }; }
describe("Fable Convex authorization", () => {
  it("bootstraps once and rejects a conflicting replay", () => { const s = { ...state(), bootstrapReceipts: [] } as BootstrapState; const first = bootstrapAccountToState(s, identity, "boot", "a"); expect(first.status).toBe("created"); expect(bootstrapAccountToState(s, identity, "boot", "a")).toEqual(first); expect(bootstrapAccountToState(s, identity, "boot", "other")).toMatchObject({ status: "conflict" }); expect(s.workspaces).toHaveLength(3); });
  it("does not require or accept an organization claim", () => { expect(requireCanRead(state(), identity, "ws-a").user.internalUserId).toBe("u-editor"); });
  it("denies membership isolation opaquely", () => { expect(() => requireCanRead(state(), identity, "ws-b")).toThrow(/membership/i); });
  it("enforces role and active device links", () => { const s = state(); expect(() => requireCanManageMembers(s, identity, "ws-a")).toThrow(); expect(applyOutboxMutationToState(s, { ...identity, subject: "external-viewer" }, mutation({ deviceId: "d-viewer", idempotencyKey: "ws-a:d-viewer:one" }))).toMatchObject({ code: "permission-denied" }); s.deviceLinks[0].status = "revoked"; expect(applyOutboxMutationToState(s, identity, mutation())).toMatchObject({ code: "device-inactive" }); });
  it("protects the final active owner", () => { const owner = state().memberships[0]; expect(() => ensureNotLastOwner({ memberships: [owner] }, owner, "editor")).toThrow(/owner/i); });
  it("replays idempotently and rejects stale cross-workspace writes", () => { const s = state(); const first = applyOutboxMutationToState(s, identity, mutation()); expect(applyOutboxMutationToState(s, identity, mutation({ payload: { name: "retry" } }))).toEqual(first); expect(s.projects).toHaveLength(1); expect(applyOutboxMutationToState(s, identity, mutation({ workspaceId: "ws-b", idempotencyKey: "ws-b:d-editor:one", clientMutationId: "two" }))).toMatchObject({ code: "membership-required" }); });
  it("tombstones beat stale update resurrection", () => { const s = state(); applyOutboxMutationToState(s, identity, mutation()); applyOutboxMutationToState(s, identity, mutation({ clientMutationId: "delete", idempotencyKey: "ws-a:d-editor:delete", operation: "delete", baseRevision: 1 })); expect(applyOutboxMutationToState(s, identity, mutation({ clientMutationId: "stale", idempotencyKey: "ws-a:d-editor:stale", operation: "update", baseRevision: 1 }))).toMatchObject({ code: "conflict" }); });
});
