import { describe, expect, it } from "vitest";
import { applyOutboxMutationToState, bootstrapAccountToState, ensureDeviceLink, ensureInvitationTarget, ensureNotLastOwner, listAccessibleWorkspaces, listAccountDevices, requireCanManageMembers, requireCanRead, revokeAccountDeviceToState, type BootstrapState, type CloudState, type OutboxMutationArgs } from "./cloudPolicy";
const identity = { provider: "clerk" as const, normalizedIssuer: "https://issuer.example", subject: "external-editor" };
function state(): CloudState { return { users: [{ internalUserId: "u-owner", status: "active" }, { internalUserId: "u-editor", status: "active" }, { internalUserId: "u-viewer", status: "active" }], identityLinks: [{ provider: "clerk", normalizedIssuer: identity.normalizedIssuer, subject: "external-owner", internalUserId: "u-owner", status: "active" }, { ...identity, internalUserId: "u-editor", status: "active" }, { provider: "clerk", normalizedIssuer: identity.normalizedIssuer, subject: "external-viewer", internalUserId: "u-viewer", status: "active" }], workspaces: [{ workspaceId: "ws-a", name: "A", status: "active", revision: 0, policyRevision: 1 }, { workspaceId: "ws-b", name: "B", status: "active", revision: 0, policyRevision: 1 }], memberships: [{ memberId: "m-owner", workspaceId: "ws-a", internalUserId: "u-owner", role: "owner", status: "active", revision: 1 }, { memberId: "m-editor", workspaceId: "ws-a", internalUserId: "u-editor", role: "editor", status: "active", revision: 1 }, { memberId: "m-viewer", workspaceId: "ws-a", internalUserId: "u-viewer", role: "viewer", status: "active", revision: 1 }], devices: [{ deviceId: "d-editor", internalUserId: "u-editor", status: "active" }, { deviceId: "d-viewer", internalUserId: "u-viewer", status: "active" }], deviceLinks: [{ workspaceId: "ws-a", deviceId: "d-editor", internalUserId: "u-editor", memberId: "m-editor", status: "active" }, { workspaceId: "ws-a", deviceId: "d-viewer", internalUserId: "u-viewer", memberId: "m-viewer", status: "active" }], projects: [], tombstones: [], idempotencyKeys: [] }; }
function mutation(overrides: Partial<OutboxMutationArgs> = {}): OutboxMutationArgs { return { workspaceId: "ws-a", deviceId: "d-editor", clientMutationId: "one", idempotencyKey: "ws-a:d-editor:one", baseRevision: 0, recordType: "project", recordId: "p-one", operation: "create", ...overrides }; }
describe("Fable Convex authorization", () => {
  it("bootstraps once and rejects a conflicting replay", () => { const s = { ...state(), bootstrapReceipts: [] } as BootstrapState; const newIdentity = { ...identity, subject: "external-new" }; const first = bootstrapAccountToState(s, newIdentity, "boot", "a"); expect(first.status).toBe("created"); expect(bootstrapAccountToState(s, newIdentity, "boot", "a")).toEqual(first); expect(bootstrapAccountToState(s, newIdentity, "boot", "other")).toMatchObject({ status: "conflict" }); expect(s.workspaces).toHaveLength(3); });
  it("creates an initial owner workspace even when an invited user already has another membership", () => { const s = { ...state(), bootstrapReceipts: [] } as BootstrapState; const result = bootstrapAccountToState(s, identity, "bootstrap"); expect(result).toMatchObject({ status: "existing", internalUserId: "u-editor" }); expect(s.users.find((user) => user.internalUserId === "u-editor")?.initialWorkspaceId).toBe(result.workspaceId); expect(s.memberships.filter((membership) => membership.internalUserId === "u-editor" && membership.status === "active")).toHaveLength(2); expect(s.memberships.find((membership) => membership.memberId === result.memberId)).toMatchObject({ role: "owner", workspaceId: result.workspaceId }); });
  it("lists only active, unambiguous workspace DTOs in a deterministic order", () => { const s = state(); s.memberships.push({ memberId: "m-editor-b", workspaceId: "ws-b", internalUserId: "u-editor", role: "viewer", status: "active", revision: 1 }); s.workspaces.push({ workspaceId: "ws-disabled", name: "Disabled", status: "deleted", revision: 0, policyRevision: 1 }); s.memberships.push({ memberId: "m-editor-disabled", workspaceId: "ws-disabled", internalUserId: "u-editor", role: "owner", status: "active", revision: 1 }); const listed = listAccessibleWorkspaces(s, identity); expect(listed.map((workspace) => workspace.workspaceId)).toEqual(["ws-a", "ws-b"]); expect(Object.keys(listed[0]).sort()).toEqual(["memberId", "membershipRevision", "name", "policyRevision", "revision", "role", "workspaceId"]); });
  it("does not require or accept an organization claim", () => { expect(requireCanRead(state(), identity, "ws-a").user.internalUserId).toBe("u-editor"); });
  it("fails closed when an external identity tuple is ambiguous", () => { const s = state(); s.identityLinks.push({ ...identity, internalUserId: "u-owner", status: "active" }); expect(() => requireCanRead(s, identity, "ws-a")).toThrow(/ambiguous|conflict/i); });
  it("rejects unavailable, duplicate, or already-member invitation targets", () => { expect(() => ensureInvitationTarget("disabled", false, undefined)).toThrow(/unavailable/i); expect(() => ensureInvitationTarget("active", true, undefined)).toThrow(/unavailable/i); expect(() => ensureInvitationTarget("active", false, "active")).toThrow(/unavailable/i); });
  it("does not reactivate revoked devices or relink them to another member", () => { expect(() => ensureDeviceLink({ internalUserId: "u-editor", status: "revoked" }, undefined, "u-editor", "m-editor")).toThrow(/unavailable/i); expect(() => ensureDeviceLink({ internalUserId: "u-editor", status: "active" }, { internalUserId: "u-editor", memberId: "m-editor", status: "active" }, "u-editor", "m-viewer")).toThrow(/unavailable/i); expect(() => ensureDeviceLink({ internalUserId: "u-editor", status: "active" }, { internalUserId: "u-editor", memberId: "m-editor", status: "active" }, "u-editor", "m-editor")).not.toThrow(); });
  it("lists and revokes devices at the account boundary, including every workspace link", () => { const s = state(); s.devices[0] = { ...s.devices[0], kind: "desktop", label: "Editor laptop", registeredAt: 10, lastSeenAt: 20 }; s.deviceLinks.push({ workspaceId: "ws-b", deviceId: "d-editor", internalUserId: "u-editor", memberId: "m-editor", status: "active" }); expect(listAccountDevices(s, identity)).toEqual([{ deviceId: "d-editor", kind: "desktop", label: "Editor laptop", status: "active", registeredAt: 10, lastSeenAt: 20 }]); expect(revokeAccountDeviceToState(s, identity, "d-editor", 30)).toEqual({ deviceId: "d-editor", status: "revoked", revokedWorkspaceLinks: 2 }); expect(s.devices[0]).toMatchObject({ status: "revoked", revokedAt: 30 }); expect(s.deviceLinks.filter((link) => link.deviceId === "d-editor").every((link) => link.status === "revoked")).toBe(true); expect(applyOutboxMutationToState(s, identity, mutation())).toMatchObject({ code: "device-inactive" }); });
  it("never lets one account list or revoke another account's device", () => { const s = state(); expect(listAccountDevices(s, { ...identity, subject: "external-viewer" })).toEqual([]); expect(() => revokeAccountDeviceToState(s, { ...identity, subject: "external-viewer" }, "d-editor")).toThrow(/unavailable/i); });
  it("denies membership isolation opaquely", () => { expect(() => requireCanRead(state(), identity, "ws-b")).toThrow(/membership/i); });
  it("enforces role and active device links", () => { const s = state(); expect(() => requireCanManageMembers(s, identity, "ws-a")).toThrow(); expect(applyOutboxMutationToState(s, { ...identity, subject: "external-viewer" }, mutation({ deviceId: "d-viewer", idempotencyKey: "ws-a:d-viewer:one" }))).toMatchObject({ code: "permission-denied" }); s.deviceLinks[0].status = "revoked"; expect(applyOutboxMutationToState(s, identity, mutation())).toMatchObject({ code: "device-inactive" }); });
  it("protects the final active owner", () => { const owner = state().memberships[0]; expect(() => ensureNotLastOwner({ memberships: [owner] }, owner, "editor")).toThrow(/owner/i); });
  it("replays idempotently and rejects stale cross-workspace writes", () => { const s = state(); const first = applyOutboxMutationToState(s, identity, mutation()); expect(applyOutboxMutationToState(s, identity, mutation({ payload: { name: "retry" } }))).toEqual(first); expect(s.projects).toHaveLength(1); expect(applyOutboxMutationToState(s, identity, mutation({ workspaceId: "ws-b", idempotencyKey: "ws-b:d-editor:two", clientMutationId: "two" }))).toMatchObject({ code: "membership-required" }); });
  it("tombstones beat stale update resurrection", () => { const s = state(); applyOutboxMutationToState(s, identity, mutation()); applyOutboxMutationToState(s, identity, mutation({ clientMutationId: "delete", idempotencyKey: "ws-a:d-editor:delete", operation: "delete", baseRevision: 1 })); expect(applyOutboxMutationToState(s, identity, mutation({ clientMutationId: "stale", idempotencyKey: "ws-a:d-editor:stale", operation: "update", baseRevision: 1 }))).toMatchObject({ code: "conflict" }); });
});
