import { mutationGeneric } from "convex/server";
import { v } from "convex/values";
import { requireActiveDevice } from "./authorization";
import type { MutationResult } from "./cloudPolicy";

export const applyOutboxMutation = mutationGeneric({ args: { workspaceId: v.string(), deviceId: v.string(), clientMutationId: v.string(), idempotencyKey: v.string(), baseRevision: v.number(), recordType: v.literal("project"), recordId: v.string(), operation: v.union(v.literal("create"), v.literal("update"), v.literal("delete")), payload: v.optional(v.object({ name: v.optional(v.string()) })) }, handler: async (ctx, args): Promise<MutationResult> => {
  const expected = `${args.workspaceId}:${args.deviceId}:${args.clientMutationId}`; if (args.idempotencyKey !== expected) return { status: "rejected", code: "idempotency-conflict", message: "The shared record is unavailable." };
  const replay = await ctx.db.query("idempotency_keys").withIndex("by_mutation", (q: any) => q.eq("workspaceId", args.workspaceId).eq("deviceId", args.deviceId).eq("clientMutationId", args.clientMutationId)).first(); if (replay) return replay.result as MutationResult;
  const now = Date.now(); let authz: any;
  try { authz = await requireActiveDevice(ctx, args.workspaceId, args.deviceId); if (authz.membership.role === "viewer") throw new Error("permission-denied"); } catch { return store(ctx, args, { status: "rejected", code: "permission-denied", message: "The shared record is unavailable." }, now); }
  const workspace = authz.workspace; const tombstone = await ctx.db.query("tombstones").withIndex("by_record", (q: any) => q.eq("workspaceId", args.workspaceId).eq("recordType", args.recordType).eq("recordId", args.recordId)).first();
  const existing = await ctx.db.query("shared_projects").withIndex("by_workspace_record", (q: any) => q.eq("workspaceId", args.workspaceId).eq("projectId", args.recordId)).first(); const revision = workspace.revision + 1;
  if ((tombstone && args.operation !== "delete") || (args.operation !== "create" && (!existing || existing.deletedAt || existing.revision !== args.baseRevision)) || (args.operation === "create" && existing && !existing.deletedAt)) return store(ctx, args, { status: "rejected", code: "conflict", message: "The shared record is unavailable." }, now, authz);
  if (args.operation === "create") await ctx.db.insert("shared_projects", { workspaceId: args.workspaceId, projectId: args.recordId, name: args.payload?.name?.trim() || "Untitled project", revision, createdByInternalUserId: authz.user.internalUserId, createdByDeviceId: args.deviceId, createdAt: now, updatedAt: now });
  else if (args.operation === "update") await ctx.db.patch(existing._id, { name: args.payload?.name?.trim() || existing.name, revision, updatedAt: now });
  else { await ctx.db.patch(existing._id, { revision, updatedAt: now, deletedAt: now }); await ctx.db.insert("tombstones", { workspaceId: args.workspaceId, recordType: "project", recordId: args.recordId, revision, deletedAt: now, actorInternalUserId: authz.user.internalUserId, actorDeviceId: args.deviceId, reasonClass: "user-delete" }); }
  await ctx.db.patch(workspace._id, { revision, updatedAt: now }); return store(ctx, args, { status: "accepted", revision, recordType: "project", recordId: args.recordId }, now, authz);
} });
async function store(ctx: any, args: any, result: MutationResult, now: number, authz?: any) { await ctx.db.insert("idempotency_keys", { workspaceId: args.workspaceId, deviceId: args.deviceId, clientMutationId: args.clientMutationId, idempotencyKey: args.idempotencyKey, status: result.status, result, createdAt: now }); if (authz) await ctx.db.insert("mutation_audit", { workspaceId: args.workspaceId, internalUserId: authz.user.internalUserId, memberId: authz.membership.memberId, deviceId: args.deviceId, clientMutationId: args.clientMutationId, recordType: "project", recordId: args.recordId, operation: args.operation, status: result.status, revision: result.status === "accepted" ? result.revision : undefined, createdAt: now }); return result; }
